export const PRODUCTS = [
  {
    id: '1',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '2',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: ['traditional', 'with milk'],
    amount: 0,
  },
  {
    id: '3',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '4',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '5',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '6',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '7',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
  {
    id: '8',
    name: 'Traditional express',
    description: 'The traditional coffee made with hot water and ground beans',
    imageUrl: '/coffee.svg',
    price: 9.9,
    category: 'traditional',
    amount: 0,
  },
]
